language: python
sudo: required
python:
    - 2.7.8
    #- 3.2
    - 3.3
    #- 3.4
    #- 3.5
    - "pypy"

os:
  - linux

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - travis_retry pip install pylint codeclimate-test-reporter
  - travis_retry pip install pytest-cov coverage coveralls codacy-coverage

script:
   coverage run --source=pyBDM setup.py test

after_success:
  - pylint app
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
  - codeclimate-test-reporter

